name: Security Pipeline

on:
  push:
    branches:
      - main

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Recuperation du code
        uses: actions/checkout@v4

      - name: Test du pipeline
        run: echo "Le pipeline de securite fonctionne"
